<?php
_('Performs a guaranteed hit for the next attack. 50 seconds cooldown.');
_('Performs a guaranteed hit for the next 2 attacks. 50 seconds cooldown.');
_('Performs a guaranteed hit for the next 3 attacks. 44 seconds cooldown.');
_('Performs a guaranteed hit for the next 3 attacks. 32 seconds cooldown.');
_('Performs a guaranteed hit for the next 3 attacks. 24 seconds cooldown.');
_('Makes your skin as hard as stone! Damage taken by the next 5 attacks is reduced by 3&#37;. 20 seconds cooldown.');
_('Makes your skin as hard as stone! Damage taken by the next 5 attacks is reduced by 6&#37;. 20 seconds cooldown.');
_('Makes your skin as hard as stone! Damage taken by the next 5 attacks is reduced by 9&#37;. 20 seconds cooldown.');
_('Makes your skin as hard as stone! Damage taken by the next 5 attacks is reduced by 12&#37;. 20 seconds cooldown.');
_('Makes your skin as hard as stone! Damage taken by the next 5 attacks is reduced by 15&#37;. 20 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 50 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 45 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 40 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 35 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 30 seconds cooldown.');
_('Dodges the next 5 attacks, reducing damage taken by 18&#37;. 20 seconds cooldown.');
_('Dodges the next 5 attacks, reducing damage taken by 21&#37;. 20 seconds cooldown.');
_('Dodges the next 5 attacks, reducing damage taken by 24&#37;. 20 seconds cooldown.');
_('Dodges the next 5 attacks, reducing damage taken by 27&#37;. 20 seconds cooldown.');
_('Dodges the next 5 attacks, reducing damage taken by 30&#37;. 20 seconds cooldown.');
_('The years of training have sharpened your weapon skills. Performs a guaranteed hit and increases damage dealt by 4&#37; for the next 3 attacks. 24 seconds cooldown.');
_('The years of training have sharpened your weapon skills. Performs a guaranteed hit and increases damage dealt by 8&#37; for the next 3 attacks. 24 seconds cooldown.');
_('The years of training have sharpened your weapon skills. Performs a guaranteed hit and increases damage dealt by 12&#37; for the next 3 attacks. 24 seconds cooldown.');
_('The years of training have sharpened your weapon skills. Performs a guaranteed hit and increases damage dealt by 16&#37; for the next 3 attacks. 24 seconds cooldown.');
_('The years of training have sharpened your weapon skills. Performs a guaranteed hit and increases damage dealt by 20&#37; for the next 3 attacks. 24 seconds cooldown.');
_('Taunts all enemies in 3 yard range, forcing them to attack you. 50 seconds cooldown.');
_('Taunts all enemies in 3 yard range, forcing them to attack you. 45 seconds cooldown.');
_('Taunts all enemies in 3 yard range, forcing them to attack you. 40 seconds cooldown.');
_('Taunts all enemies in 3 yard range, forcing them to attack you. 35 seconds cooldown.');
_('Taunts all enemies in 3 yard range, forcing them to attack you. 30 seconds cooldown.');
_('A sweeping attack that strikes your target and an additional nearby enemy with 72&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('A sweeping attack that strikes your target and an additional nearby enemy with 76&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('A sweeping attack that strikes your target and an additional nearby enemy with 80&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('A sweeping attack that strikes your target and an additional nearby enemy with 84&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('A sweeping attack that strikes your target and an additional nearby enemy with 88&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Raises your shield and guards yourself! Damage taken is reduced by 33&#37; for 10 seconds. 20 seconds cooldown.');
_('Raises your shield and guards yourself! Damage taken is reduced by 36&#37; for 10 seconds. 20 seconds cooldown.');
_('Raises your shield and guards yourself! Damage taken is reduced by 39&#37; for 10 seconds. 20 seconds cooldown.');
_('Raises your shield and guards yourself! Damage taken is reduced by 42&#37; for 10 seconds. 20 seconds cooldown.');
_('Raises your shield and guards yourself! Damage taken is reduced by 45&#37; for 10 seconds. 20 seconds cooldown.');
_('Focuses your mana to release it with a powerful arcane strike. Consumes all your mana and converts 0.37 damage per mana point additional to your next attack. 28 seconds cooldown.');
_('Focuses your mana to release it with a powerful arcane strike. Consumes all your mana and converts 0.40 damage per mana point additional to your next attack. 28 seconds cooldown.');
_('Focuses your mana to release it with a powerful arcane strike. Consumes all your mana and converts 0.43 damage per mana point additional to your next attack. 28 seconds cooldown.');
_('Focuses your mana to release it with a powerful arcane strike. Consumes all your mana and converts 0.46 damage per mana point additional to your next attack. 28 seconds cooldown.');
_('Focuses your mana to release it with a powerful arcane strike. Consumes all your mana and converts 0.50 damage per mana point additional to your next attack. 28 seconds cooldown.');
_('Performs a guaranteed hit and strikes your target and an additional nearby enemy with 73&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Performs a guaranteed hit and strikes your target and an additional nearby enemy with 76&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Performs a guaranteed hit and strikes your target and an additional nearby enemy with 79&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Performs a guaranteed hit and strikes your target and an additional nearby enemy with 82&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Performs a guaranteed hit and strikes your target and an additional nearby enemy with 85&#37; damage for the next 2 attacks. 25 seconds cooldown.');
_('Parries your enemies, increasing the chance to evade the next 4 incoming attacks. Every skill level raises the chance to evade by a medium amount. 28 seconds cooldown.');
_('You become enraged, increasing the damage dealt by 33&#37; for 10 seconds. 20 seconds cooldown.');
_('You become enraged, increasing the damage dealt by 36&#37; for 10 seconds. 20 seconds cooldown.');
_('You become enraged, increasing the damage dealt by 39&#37; for 10 seconds. 20 seconds cooldown.');
_('You become enraged, increasing the damage dealt by 42&#37; for 10 seconds. 20 seconds cooldown.');
_('You become enraged, increasing the damage dealt by 45&#37; for 10 seconds. 20 seconds cooldown.');
_('Knocks the head of your enemy with the hilt of your weapon, performing a guaranteed hit and incapacitating your target for 2.0 seconds with your next attack. 30 seconds cooldown.');
_('Knocks the head of your enemy with the hilt of your weapon, performing a guaranteed hit and incapacitating your target for 2.5 seconds with your next attack. 30 seconds cooldown.');
_('Knocks the head of your enemy with the hilt of your weapon, performing a guaranteed hit and incapacitating your target for 3.0 seconds with your next attack. 30 seconds cooldown.');
_('Knocks the head of your enemy with the hilt of your weapon, performing a guaranteed hit and incapacitating your target for 3.5 seconds with your next attack. 30 seconds cooldown.');
_('Knocks the head of your enemy with the hilt of your weapon, performing a guaranteed hit and incapacitating your target for 4.0 seconds with your next attack. 30 seconds cooldown.');
_('Performs a stacked attack for the next 5 attacks. A stacked attack allows you to attack an enemy, even when sharing the tile with other players. 40 seconds cooldown.');
_('Performs a stacked attack for the next 5 attacks. A stacked attack allows you to attack an enemy, even when sharing the tile with other players. 35 seconds cooldown.');
_('Performs a stacked attack for the next 5 attacks. A stacked attack allows you to attack an enemy, even when sharing the tile with other players. 30 seconds cooldown.');
_('Performs a stacked attack for the next 5 attacks. A stacked attack allows you to attack an enemy, even when sharing the tile with other players. 25 seconds cooldown.');
_('Performs a stacked attack for the next 5 attacks. A stacked attack allows you to attack an enemy, even when sharing the tile with other players. 20 seconds cooldown.');
_('Equips yourself with a dwarven warden armour that adds an additional piece of armour with 80&#37; of your current protection for the next 6 incoming attacks. 18 seconds cooldown.');
_('Equips yourself with a dwarven warden armour that adds an additional piece of armour with 85&#37; of your current protection for the next 6 incoming attacks. 18 seconds cooldown.');
_('Equips yourself with a dwarven warden armour that adds an additional piece of armour with 90&#37; of your current protection for the next 6 incoming attacks. 18 seconds cooldown.');
_('Equips yourself with a dwarven warden armour that adds an additional piece of armour with 95&#37; of your current protection for the next 6 incoming attacks. 18 seconds cooldown.');
_('Equips yourself with a dwarven warden armour that adds an additional piece of armour with 100&#37; of your current protection for the next 6 incoming attacks. 18 seconds cooldown.');
_('Releases a bladestorm on your target, increasing damage dealt by 3&#37; and performing an additional strike on your target for the next 3 attacks. 24 seconds cooldown.');
_('Releases a bladestorm on your target, increasing damage dealt by 5&#37; and performing an additional strike on your target for the next 3 attacks. 24 seconds cooldown.');
_('Releases a bladestorm on your target, increasing damage dealt by 8&#37; and performing an additional strike on your target for the next 3 attacks. 24 seconds cooldown.');
_('Releases a bladestorm on your target, increasing damage dealt by 10&#37; and performing an additional strike on your target for the next 3 attacks. 24 seconds cooldown.');
_('Releases a bladestorm on your target, increasing damage dealt by 13&#37; and performing an additional strike on your target for the next 3 attacks. 24 seconds cooldown.');
_('Temporarily improves your reflexes, protects you from enemy debuffs for 10 seconds. 50 seconds cooldown.');
_('Temporarily improves your reflexes, protects you from enemy debuffs for 10 seconds. 45 seconds cooldown.');
_('Temporarily improves your reflexes, protects you from enemy debuffs for 10 seconds. 40 seconds cooldown.');
_('Temporarily improves your reflexes, protects you from enemy debuffs for 10 seconds. 35 seconds cooldown.');
_('Temporarily improves your reflexes, protects you from enemy debuffs for 10 seconds. 30 seconds cooldown.');
_('A steady stream of mana creates a shield against enemy attacks, preventing damage taken and draining 1.20 mana per damage point for 30 seconds. 60 seconds cooldown.');
_('A steady stream of mana creates a shield against enemy attacks, preventing damage taken and draining 1.15 mana per damage point for 30 seconds. 60 seconds cooldown.');
_('A steady stream of mana creates a shield against enemy attacks, preventing damage taken and draining 1.10 mana per damage point for 30 seconds. 60 seconds cooldown.');
_('A steady stream of mana creates a shield against enemy attacks, preventing damage taken and draining 1.05 mana per damage point for 30 seconds. 60 seconds cooldown.');
_('A steady stream of mana creates a shield against enemy attacks, preventing damage taken and draining 1.00 mana per damage point for 30 seconds. 60 seconds cooldown.');
_('Swirls your weapon around in a circle, performing a guaranteed hit and striking your target and 3 additional nearby enemies with 41&#37; damage for the next 3 attacks. 24 seconds cooldown.');
_('Swirls your weapon around in a circle, performing a guaranteed hit and striking your target and 3 additional nearby enemies with 42&#37; damage for the next 3 attacks. 24 seconds cooldown.');
_('Swirls your weapon around in a circle, performing a guaranteed hit and striking your target and 3 additional nearby enemies with 43&#37; damage for the next 3 attacks. 24 seconds cooldown.');
_('Swirls your weapon around in a circle, performing a guaranteed hit and striking your target and 3 additional nearby enemies with 44&#37; damage for the next 3 attacks. 24 seconds cooldown.');
_('Swirls your weapon around in a circle, performing a guaranteed hit and striking your target and 3 additional nearby enemies with 45&#37; damage for the next 3 attacks. 24 seconds cooldown.');
_('Enters an offensive stance, increasing the damage dealt by 21&#37; and the chance to hit your enemy with attacks for 60 seconds. Every skill level raises the chance to hit by a medium amount. 30 seconds cooldown.');
_('Enters an offensive stance, increasing the damage dealt by 22&#37; and the chance to hit your enemy with attacks for 60 seconds. Every skill level raises the chance to hit by a medium amount. 30 seconds cooldown.');
_('Enters an offensive stance, increasing the damage dealt by 23&#37; and the chance to hit your enemy with attacks for 60 seconds. Every skill level raises the chance to hit by a medium amount. 30 seconds cooldown.');
_('Enters an offensive stance, increasing the damage dealt by 24&#37; and the chance to hit your enemy with attacks for 60 seconds. Every skill level raises the chance to hit by a medium amount. 30 seconds cooldown.');
_('Enters an offensive stance, increasing the damage dealt by 25&#37; and the chance to hit your enemy with attacks for 60 seconds. Every skill level raises the chance to hit by a medium amount. 30 seconds cooldown.');
_('Connects your weapon swings, performing a guaranteed hit and striking all targets in 2 yard range with 46&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. 24 seconds cooldown.');
_('Connects your weapon swings, performing a guaranteed hit and striking all targets in 2 yard range with 47&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. 24 seconds cooldown.');
_('Connects your weapon swings, performing a guaranteed hit and striking all targets in 2 yard range with 48&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. 24 seconds cooldown.');
_('Connects your weapon swings, performing a guaranteed hit and striking all targets in 2 yard range with 49&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. 24 seconds cooldown.');
_('Connects your weapon swings, performing a guaranteed hit and striking all targets in 2 yard range with 50&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. 24 seconds cooldown.');
_('Take cover behind your shield, absorbs 75&#37; of the next 170 damage taken. 90 seconds cooldown.');
_('Take cover behind your shield, absorbs 75&#37; of the next 180 damage taken. 90 seconds cooldown.');
_('Take cover behind your shield, absorbs 75&#37; of the next 190 damage taken. 90 seconds cooldown.');
_('Take cover behind your shield, absorbs 75&#37; of the next 200 damage taken. 90 seconds cooldown.');
_('Take cover behind your shield, absorbs 75&#37; of the next 210 damage taken. 90 seconds cooldown.');
_('A surprising smash makes your enemy loose concentration, granting a chance to discharge target offensive skill by 80&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('A surprising smash makes your enemy loose concentration, granting a chance to discharge target offensive skill by 85&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('A surprising smash makes your enemy loose concentration, granting a chance to discharge target offensive skill by 90&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('A surprising smash makes your enemy loose concentration, granting a chance to discharge target offensive skill by 95&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('A surprising smash makes your enemy loose concentration, granting a chance to discharge target offensive skill by 100&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Smashes the enemy with a powerful attack, performing a guaranteed hit and increasing damage dealt by 84&#37; for the next 3 attacks. 30 seconds cooldown.');
_('Smashes the enemy with a powerful attack, performing a guaranteed hit and increasing damage dealt by 88&#37; for the next 3 attacks. 30 seconds cooldown.');
_('Smashes the enemy with a powerful attack, performing a guaranteed hit and increasing damage dealt by 92&#37; for the next 3 attacks. 30 seconds cooldown.');
_('Smashes the enemy with a powerful attack, performing a guaranteed hit and increasing damage dealt by 96&#37; for the next 3 attacks. 30 seconds cooldown.');
_('Smashes the enemy with a powerful attack, performing a guaranteed hit and increasing damage dealt by 100&#37; for the next 3 attacks. 30 seconds cooldown.');
_('Deflects enemy spells with your shield, protects you against the next 2 aggressive spells or debuffs. 50 seconds cooldown.');
_('Deflects enemy spells with your shield, protects you against the next 2 aggressive spells or debuffs. 45 seconds cooldown.');
_('Deflects enemy spells with your shield, protects you against the next 2 aggressive spells or debuffs. 40 seconds cooldown.');
_('Deflects enemy spells with your shield, protects you against the next 2 aggressive spells or debuffs. 35 seconds cooldown.');
_('Deflects enemy spells with your shield, protects you against the next 2 aggressive spells or debuffs. 30 seconds cooldown.');
_('Gathers your power before striking with a mighty blow, reducing the damage dealt by 45&#37; for the next attack. The following 3 attacks will perform a guaranteed hit and deal the maximum amount of damage. 22 seconds cooldown.');
_('Gathers your power before striking with a mighty blow, reducing the damage dealt by 30&#37; for the next attack. The following 3 attacks will perform a guaranteed hit and deal the maximum amount of damage. 22 seconds cooldown.');
_('Gathers your power before striking with a mighty blow, reducing the damage dealt by 15&#37; for the next attack. The following 3 attacks will perform a guaranteed hit and deal the maximum amount of damage. 22 seconds cooldown.');
_('Gathers your power before striking with a mighty blow, reducing the damage dealt by 0&#37; for the next attack. The following 3 attacks will perform a guaranteed hit and deal the maximum amount of damage. 22 seconds cooldown.');
_('Gathers your power before striking with a mighty blow, increasing the damage dealt by 15&#37; for the next attack. The following 3 attacks will perform a guaranteed hit and deal the maximum amount of damage. 22 seconds cooldown.');
_('Enters a defensive stance, increasing the chance to evade enemy attacks for 60 seconds. Every skill level raises the chance to evade by a medium amount. 30 seconds cooldown.');
_('Performs a guaranteed hit and strikes all targets in 2 yard range with 56&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. Afterwards all enemies search for a new target. 24 seconds cooldown.');
_('Performs a guaranteed hit and strikes all targets in 2 yard range with 57&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. Afterwards all enemies search for a new target. 24 seconds cooldown.');
_('Performs a guaranteed hit and strikes all targets in 2 yard range with 58&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. Afterwards all enemies search for a new target. 24 seconds cooldown.');
_('Performs a guaranteed hit and strikes all targets in 2 yard range with 59&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. Afterwards all enemies search for a new target. 24 seconds cooldown.');
_('Performs a guaranteed hit and strikes all targets in 2 yard range with 60&#37; damage for the next 3 attacks. All enemies in 2 yard distance will only receive half of the damage. Afterwards all enemies search for a new target. 24 seconds cooldown.');
_('Reduces damage taken by 66&#37; and increases the chance to evade enemy attacks for 30 seconds. Every skill level raises the chance to evade by a small amount. 30 seconds cooldown.');
_('Reduces damage taken by 67&#37; and increases the chance to evade enemy attacks for 30 seconds. Every skill level raises the chance to evade by a small amount. 30 seconds cooldown.');
_('Reduces damage taken by 68&#37; and increases the chance to evade enemy attacks for 30 seconds. Every skill level raises the chance to evade by a small amount. 30 seconds cooldown.');
_('Reduces damage taken by 69&#37; and increases the chance to evade enemy attacks for 30 seconds. Every skill level raises the chance to evade by a small amount. 30 seconds cooldown.');
_('Reduces damage taken by 70&#37; and increases the chance to evade enemy attacks for 30 seconds. Every skill level raises the chance to evade by a small amount. 30 seconds cooldown.');
_('Increases the damage dealt by 16&#37;. Also increases the chance to hit your enemy with attacks and to evade enemy attacks for 60 seconds. Every skill level raises the chance to hit and to evade by a small amount. 30 seconds cooldown.');
_('Increases the damage dealt by 17&#37;. Also increases the chance to hit your enemy with attacks and to evade enemy attacks for 60 seconds. Every skill level raises the chance to hit and to evade by a small amount. 30 seconds cooldown.');
_('Increases the damage dealt by 18&#37;. Also increases the chance to hit your enemy with attacks and to evade enemy attacks for 60 seconds. Every skill level raises the chance to hit and to evade by a small amount. 30 seconds cooldown.');
_('Increases the damage dealt by 19&#37;. Also increases the chance to hit your enemy with attacks and to evade enemy attacks for 60 seconds. Every skill level raises the chance to hit and to evade by a small amount. 30 seconds cooldown.');
_('Increases the damage dealt by 20&#37;. Also increases the chance to hit your enemy with attacks and to evade enemy attacks for 60 seconds. Every skill level raises the chances to hit and to evade by a small amount. 30 seconds cooldown.');
_('Blocks an enemy attack with your shield and counter them, reducing damage taken by 63&#37; and retaliating 88&#37; of the original damage for the next 5 enemy attacks. 20 seconds cooldown.');
_('Blocks an enemy attack with your shield and counter them, reducing damage taken by 66&#37; and retaliating 92&#37; of the original damage for the next 5 enemy attacks. 20 seconds cooldown.');
_('Blocks an enemy attack with your shield and counter them, reducing damage taken by 69&#37; and retaliating 96&#37; of the original damage for the next 5 enemy attacks. 20 seconds cooldown.');
_('Blocks an enemy attack with your shield and counter them, reducing damage taken by 72&#37; and retaliating 100&#37; of the original damage for the next 5 enemy attacks. 20 seconds cooldown.');
_('Blocks an enemy attack with your shield and counter them, reducing damage taken by 75&#37; and retaliating 104&#37; of the original damage for the next 5 enemy attacks. 20 seconds cooldown.');
