<?php
_('Increases the minimum heal amount of your next 2 heal spells by 8&#37;. 20 seconds cooldown.');
_('Increases the minimum heal amount of your next 2 heal spells by 15&#37;. 20 seconds cooldown.');
_('Increases the minimum heal amount of your next 2 heal spells by 23&#37;. 20 seconds cooldown.');
_('Increases the minimum heal amount of your next 2 heal spells by 30&#37;. 20 seconds cooldown.');
_('Increases the minimum heal amount of your next 2 heal spells by 38&#37;. 20 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 50 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 45 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at . 40 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 35 seconds cooldown.');
_('Shows the element at which the monster is most vulnerable at. 30 seconds cooldown.');
_('Enhances your dexterity, performing a guaranteed hit for the next attack. 50 seconds cooldown.');
_('Enhances your dexterity, performing a guaranteed hit for the next 2 attacks. 50 seconds cooldown.');
_('Enhances your dexterity, performing a guaranteed hit for the next 3 attacks. 44 seconds cooldown.');
_('Enhances your dexterity, performing a guaranteed hit for the next 3 attacks. 32 seconds cooldown.');
_('Enhances your dexterity, performing a guaranteed hit for the next 3 attacks. 24 seconds cooldown.');
_('Channels holy energy, increasing the healing caused by 9&#37; for your next 2 healing spells. 20 seconds cooldown.');
_('Channels holy energy, increasing the healing caused by 11&#37; for your next 2 healing spells. 20 seconds cooldown.');
_('Channels holy energy, increasing the healing caused by 12&#37; for your next 2 healing spells. 20 seconds cooldown.');
_('Channels holy energy, increasing the healing caused by 14&#37; for your next 2 healing spells. 20 seconds cooldown.');
_('Channels holy energy, increasing the healing caused by 15&#37; for your next 2 healing spells. 20 seconds cooldown.');
_('Screams in a very high tone, causing all enemies in 3 yard range to take a step back and search for a new target. 50 seconds cooldown.');
_('Screams in a very high tone, causing all enemies in 3 yard range to take a step back and search for a new target. 45 seconds cooldown.');
_('Screams in a very high tone, causing all enemies in 3 yard range to take a step back and search for a new target. 40 seconds cooldown.');
_('Screams in a very high tone, causing all enemies in 3 yard range to take a step back and search for a new target. 35 seconds cooldown.');
_('Screams in a very high tone, causing all enemies in 3 yard range to take a step back and search for a new target. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 5&#37; for the next 2 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 7&#37; for the next 2 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 9&#37; for the next 2 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 12&#37; for the next 2 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 15&#37; for the next 2 spells. 24 seconds cooldown.');
_('Enhances your weapon with holy energy, performing a guaranteed hit and increasing the damage dealt by 7&#37; for the next 5 attacks. 45 seconds cooldown.');
_('Enhances your weapon with holy energy, performing a guaranteed hit and increasing the damage dealt by 11&#37; for the next 5 attacks. 45 seconds cooldown.');
_('Enhances your weapon with holy energy, performing a guaranteed hit and increasing the damage dealt by 16&#37; for the next 5 attacks. 45 seconds cooldown.');
_('Enhances your weapon with holy energy, performing a guaranteed hit and increasing the damage dealt by 20&#37; for the next 5 attacks. 45 seconds cooldown.');
_('Enhances your weapon with holy energy, performing a guaranteed hit and increasing the damage dealt by 25&#37; for the next 5 attacks. 45 seconds cooldown.');
_('Amplifies your holy energy, causing your healing spells to heal yourself and an additional nearby ally with 61&#37; of the original heal amount for the next to 2 healing spells. 30 seconds cooldown.');
_('Amplifies your holy energy, causing your healing spells to heal yourself and an additional nearby ally with 62&#37; of the original heal amount for the next to 2 healing spells. 30 seconds cooldown.');
_('Amplifies your holy energy, causing your healing spells to heal yourself and an additional nearby ally with 63&#37; of the original heal amount for the next to 2 healing spells. 30 seconds cooldown.');
_('Amplifies your holy energy, causing your healing spells to heal yourself and an additional nearby ally with 64&#37; of the original heal amount for the next to 2 healing spells. 30 seconds cooldown.');
_('Amplifies your holy energy, causing your healing spells to heal yourself and an additional nearby ally with 65&#37; of the original heal amount for the next to 2 healing spells. 30 seconds cooldown.');
_('Shifts yourself to a meditating state, regenerating 40&#37; of your total health and mana over 15 seconds. 90 seconds cooldown.');
_('Shifts yourself to a meditating state, regenerating 45&#37; of your total health and mana over 15 seconds. 90 seconds cooldown.');
_('Shifts yourself to a meditating state, regenerating 50&#37; of your total health and mana over 15 seconds. 90 seconds cooldown.');
_('Shifts yourself to a meditating state, regenerating 55&#37; of your total health and mana over 15 seconds. 90 seconds cooldown.');
_('Shifts yourself to a meditating state, regenerating 60&#37; of your total health and mana over 15 seconds. 90 seconds cooldown.');
_('Surrounds your weapon with an electrical field, performing a guaranteed hit and incapacitating your target for 2.0 seconds with your next attack. 30 seconds cooldown.');
_('Surrounds your weapon with an electrical field, performing a guaranteed hit and incapacitating your target for 2.5 seconds with your next attack. 30 seconds cooldown.');
_('Surrounds your weapon with an electrical field, performing a guaranteed hit and incapacitating your target for 3.0 seconds with your next attack. 30 seconds cooldown.');
_('Surrounds your weapon with an electrical field, performing a guaranteed hit and incapacitating your target for 3.5 seconds with your next attack. 30 seconds cooldown.');
_('Surrounds your weapon with an electrical field, performing a guaranteed hit and incapacitating your target for 4.0 seconds with your next attack. 30 seconds cooldown.');
_('Fills yourself with a burst of holy energy, increasing the healing caused by 15&#37; for your next 3 healing spells. 20 seconds cooldown.');
_('Fills yourself with a burst of holy energy, increasing the healing caused by 16&#37; for your next 3 healing spells. 20 seconds cooldown.');
_('Fills yourself with a burst of holy energy, increasing the healing caused by 17&#37; for your next 3 healing spells. 20 seconds cooldown.');
_('Fills yourself with a burst of holy energy, increasing the healing caused by 19&#37; for your next 3 healing spells. 20 seconds cooldown.');
_('Fills yourself with a burst of holy energy, increasing the healing caused by 20&#37; for your next 3 healing spells. 20 seconds cooldown.');
_('Enhances your spells with holy energy, performing a guaranteed hit and increasing the minimum damage amount of your spells by 72&#37; for next 3 spells. 20 seconds cooldown.');
_('Enhances your spells with holy energy, performing a guaranteed hit and increasing the minimum damage amount of your spells by 84&#37; for next 3 spells. 20 seconds cooldown.');
_('Enhances your spells with holy energy, performing a guaranteed hit and increasing the minimum damage amount of your spells by 95&#37; for next 3 spells. 20 seconds cooldown.');
_('Enhances your spells with holy energy, performing a guaranteed hit and increasing the minimum damage amount of your spells by 106&#37; for next 3 spells. 20 seconds cooldown.');
_('Enhances your spells with holy energy, performing a guaranteed hit and increasing the minimum damage amount of your spells by 117&#37; for next 3 spells. 20 seconds cooldown.');
_('A mighty phrase added to your spells that sunders the armour of your enemy. Performs a guaranteed hit and reduces the armour of your enemy by 18&#37; for the next 2 spells. 24 seconds cooldown.');
_('A mighty phrase added to your spells that sunders the armour of your enemy. Performs a guaranteed hit and reduces the armour of your enemy by 21&#37; for the next 2 spells. 24 seconds cooldown.');
_('A mighty phrase added to your spells that sunders the armour of your enemy. Performs a guaranteed hit and reduces the armour of your enemy by 24&#37; for the next 2 spells. 24 seconds cooldown.');
_('A mighty phrase added to your spells that sunders the armour of your enemy. Performs a guaranteed hit and reduces the armour of your enemy by 27&#37; for the next 2 spells. 24 seconds cooldown.');
_('A mighty phrase added to your spells that sunders the armour of your enemy. Performs a guaranteed hit and reduces the armour of your enemy by 30&#37; for the next 2 spells. 24 seconds cooldown.');
_('Reduces the mana costs of your weapon by 30&#37; for the next 20 seconds. 50 seconds cooldown.');
_('Reduces the mana costs of your weapon by 35&#37; for the next 20 seconds. 50 seconds cooldown.');
_('Reduces the mana costs of your weapon by 40&#37; for the next 20 seconds. 50 seconds cooldown.');
_('Reduces the mana costs of your weapon by 45&#37; for the next 20 seconds. 50 seconds cooldown.');
_('Reduces the mana costs of your weapon by 50&#37; for the next 20 seconds. 50 seconds cooldown.');
_('A dexterous strike that performs a guaranteed hit and increases the damage dealt by 26&#37; for the next 5 attacks. 20 seconds cooldown.');
_('A dexterous strike that performs a guaranteed hit and increases the damage dealt by 31&#37; for the next 5 attacks. 20 seconds cooldown.');
_('A dexterous strike that performs a guaranteed hit and increases the damage dealt by 35&#37; for the next 5 attacks. 20 seconds cooldown.');
_('A dexterous strike that performs a guaranteed hit and increases the damage dealt by 39&#37; for the next 5 attacks. 20 seconds cooldown.');
_('A dexterous strike that performs a guaranteed hit and increases the damage dealt by 44&#37; for the next 5 attacks. 20 seconds cooldown.');
_('Surrounds you with an arcane ward, protecting yourself from enemy debuffs for 10 seconds. 50 seconds cooldown.');
_('Surrounds you with an arcane ward, protecting yourself from enemy debuffs for 10 seconds. 45 seconds cooldown.');
_('Surrounds you with an arcane ward, protecting yourself from enemy debuffs for 10 seconds. 40 seconds cooldown.');
_('Surrounds you with an arcane ward, protecting yourself from enemy debuffs for 10 seconds. 35 seconds cooldown.');
_('Surrounds you with an arcane ward, protecting yourself from enemy debuffs for 10 seconds. 30 seconds cooldown.');
_('A stream of holy energy flows through your body, causing your healing spells to heal yourself and all allies in 3 yards range with 71&#37; of the original heal amount for next to 2 healing spells. 30 seconds cooldown.');
_('A stream of holy energy flows through your body, causing your healing spells to heal yourself and all allies in 3 yards range with 72&#37; of the original heal amount for next to 2 healing spells. 30 seconds cooldown.');
_('A stream of holy energy flows through your body, causing your healing spells to heal yourself and all allies in 3 yards range with 73&#37; of the original heal amount for next to 2 healing spells. 30 seconds cooldown.');
_('A stream of holy energy flows through your body, causing your healing spells to heal yourself and all allies in 3 yards range with 74&#37; of the original heal amount for next to 2 healing spells. 30 seconds cooldown.');
_('A stream of holy energy flows through your body, causing your healing spells to heal yourself and all allies in 3 yards range with 75&#37; of the original heal amount for next to 2 healing spells. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 41&#37; for next 5 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 43&#37; for next 5 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 45&#37; for next 5 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 48&#37; for next 5 spells. 24 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt by 50&#37; for next 5 spells. 24 seconds cooldown.');
_('Enchants your weapon with a mana leeching aura, performing a guaranteed hit and draining 26&#37; of your damage dealt as mana for the next 7 attacks. 20 seconds cooldown.');
_('Enchants your weapon with a mana leeching aura, performing a guaranteed hit and draining 27&#37; of your damage dealt as mana for the next 7 attacks. 20 seconds cooldown.');
_('Enchants your weapon with a mana leeching aura, performing a guaranteed hit and draining 28&#37; of your damage dealt as mana for the next 7 attacks. 20 seconds cooldown.');
_('Enchants your weapon with a mana leeching aura, performing a guaranteed hit and draining 29&#37; of your damage dealt as mana for the next 7 attacks. 20 seconds cooldown.');
_('Enchants your weapon with a mana leeching aura, performing a guaranteed hit and draining 30&#37; of your damage dealt as mana for the next 7 attacks. 20 seconds cooldown.');
_('Confuse the mind of your enemy with a powerful spell, granting a chance to discharge target offensive skill by 80&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Confuse the mind of your enemy with a powerful spell, granting a chance to discharge target offensive skill by 85&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Confuse the mind of your enemy with a powerful spell, granting a chance to discharge target offensive skill by 90&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Confuse the mind of your enemy with a powerful spell, granting a chance to discharge target offensive skill by 95&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Confuse the mind of your enemy with a powerful spell, granting a chance to discharge target offensive skill by 100&#37; and defensive skill by 25&#37;. Monsters defensive skills can\'t be discharged. 30 seconds cooldown.');
_('Creates a magic barrier around you that either protects yourself from the next 2 aggressive spells or absorbs 60&#37; of the next 162 damage taken. First completed effect will end the skill. 60 seconds cooldown.');
_('Creates a magic barrier around you that either protects yourself from the next 2 aggressive spells or absorbs 60&#37; of the next 173 damage taken. First completed effect will end the skill. 60 seconds cooldown.');
_('Creates a magic barrier around you that either protects yourself from the next 2 aggressive spells or absorbs 60&#37; of the next 186 damage taken. First completed effect will end the skill. 60 seconds cooldown.');
_('Creates a magic barrier around you that either protects yourself from the next 2 aggressive spells or absorbs 60&#37; of the next 198 damage taken. First completed effect will end the skill. 60 seconds cooldown.');
_('Creates a magic barrier around you that either protects yourself from the next 2 aggressive spells or absorbs 60&#37; of the next 212 damage taken. First completed effect will end the skill. 60 seconds cooldown.');
_('Renews your body with holy energy, regenerating 42&#37; of your total health and mana over 30 seconds. 30 seconds cooldown.');
_('Renews your body with holy energy, regenerating 44&#37; of your total health and mana over 30 seconds. 30 seconds cooldown.');
_('Renews your body with holy energy, regenerating 46&#37; of your total health and mana over 30 seconds. 30 seconds cooldown.');
_('Renews your body with holy energy, regenerating 48&#37; of your total health and mana over 30 seconds. 30 seconds cooldown.');
_('Renews your body with holy energy, regenerating 50&#37; of your total health and mana over 30 seconds. 30 seconds cooldown.');
_('Surrounds you with a holy ward, reducing damage taken by 67&#37; for the next 7 attacks and charging the ward. When ward fades you get healed by the ward\'s charge. 30 seconds cooldown.');
_('Surrounds you with a holy ward, reducing damage taken by 69&#37; for the next 7 attacks and charging the ward. When ward fades you get healed by the ward\'s charge. 30 seconds cooldown.');
_('Surrounds you with a holy ward, reducing damage taken by 71&#37; for the next 7 attacks and charging the ward. When ward fades you get healed by the ward\'s charge. 30 seconds cooldown.');
_('Surrounds you with a holy ward, reducing damage taken by 73&#37; for the next 7 attacks and charging the ward. When ward fades you get healed by the ward\'s charge. 30 seconds cooldown.');
_('Surrounds you with a holy ward, reducing damage taken by 75&#37; for the next 7 attacks and charging the ward. When ward fades you get healed by the ward\'s charge. 30 seconds cooldown.');
_('Bridges the magical void, reducing the cooldown of your spells by 50&#37; for 18 seconds. 30 seconds cooldown.');
_('Bridges the magical void, reducing the cooldown of your spells by 50&#37; for 21 seconds. 30 seconds cooldown.');
_('Bridges the magical void, reducing the cooldown of your spells by 50&#37; for 24 seconds. 30 seconds cooldown.');
_('Bridges the magical void, reducing the cooldown of your spells by 50&#37; for 27 seconds. 30 seconds cooldown.');
_('Bridges the magical void, reducing the cooldown of your spells by 50&#37; for 30 seconds. 30 seconds cooldown.');
_('Forming a gaping hole in the magic stream allows you to cast spells at a much lower mana consumption. Reduces the mana costs of your spells by 50&#37; for the next 22 seconds. 20 seconds cooldown.');
_('Forming a gaping hole in the magic stream allows you to cast spells at a much lower mana consumption. Reduces the mana costs of your spells by 50&#37; for the next 24 seconds. 20 seconds cooldown.');
_('Forming a gaping hole in the magic stream allows you to cast spells at a much lower mana consumption. Reduces the mana costs of your spells by 50&#37; for the next 26 seconds. 20 seconds cooldown.');
_('Forming a gaping hole in the magic stream allows you to cast spells at a much lower mana consumption. Reduces the mana costs of your spells by 50&#37; for the next 28 seconds. 20 seconds cooldown.');
_('Forming a gaping hole in the magic stream allows you to cast spells at a much lower mana consumption. Reduces the mana costs of your spells by 50&#37; for the next 30 seconds. 20 seconds cooldown.');
_('Enchants your weapon with a vampiric aura, performing a guaranteed hit and draining 31&#37; of your damage dealt as heal for the next 3 attacks. 30 seconds cooldown.');
_('Enchants your weapon with a vampiric aura, performing a guaranteed hit and draining 32&#37; of your damage dealt as heal for the next 3 attacks. 30 seconds cooldown.');
_('Enchants your weapon with a vampiric aura, performing a guaranteed hit and draining 33&#37; of your damage dealt as heal for the next 3 attacks. 30 seconds cooldown.');
_('Enchants your weapon with a vampiric aura, performing a guaranteed hit and draining 34&#37; of your damage dealt as heal for the next 3 attacks. 30 seconds cooldown.');
_('Enchants your weapon with a vampiric aura, performing a guaranteed hit and draining 35&#37; of your damage dealt as heal for the next 3 attacks. 30 seconds cooldown.');
_('A masterly weapon swing that performs a guaranteed hit and increases the damage dealt by 79&#37; for next 5 attacks. 22 seconds cooldown.');
_('A masterly weapon swing that performs a guaranteed hit and increases the damage dealt by 83&#37; for next 5 attacks. 22 seconds cooldown.');
_('A masterly weapon swing that performs a guaranteed hit and increases the damage dealt by 87&#37; for next 5 attacks. 22 seconds cooldown.');
_('A masterly weapon swing that performs a guaranteed hit and increases the damage dealt by 90&#37; for next 5 attacks. 22 seconds cooldown.');
_('A masterly weapon swing that performs a guaranteed hit and increases the damage dealt by 94&#37; for next 5 attacks. 22 seconds cooldown.');
_('Enchants your armour with a mighty magic, reducing damage taken by 52&#37; and regenerating 20&#37; of your total health and mana over 30 seconds. Cooldown 30 seconds.');
_('Enchants your armour with a mighty magic, reducing damage taken by 54&#37; and regenerating 20&#37; of your total health and mana over 30 seconds. Cooldown 30 seconds.');
_('Enchants your armour with a mighty magic, reducing damage taken by 56&#37; and regenerating 20&#37; of your total health and mana over 30 seconds. Cooldown 30 seconds.');
_('Enchants your armour with a mighty magic, reducing damage taken by 58&#37; and regenerating 20&#37; of your total health and mana over 30 seconds. Cooldown 30 seconds.');
_('Enchants your armour with a mighty magic, reducing damage taken by 60&#37; and regenerating 20&#37; of your total health and mana over 30 seconds. Cooldown 30 seconds.');
_('The long study of the arcane ways have made you a master of spell casting. Performs a guaranteed hit and increases the damage dealt by 107&#37; for next 5 spells. 30 seconds cooldown.');
_('The long study of the arcane ways have made you a master of spell casting. Performs a guaranteed hit and increases the damage dealt by 110&#37; for next 5 spells. 30 seconds cooldown.');
_('The long study of the arcane ways have made you a master of spell casting. Performs a guaranteed hit and increases the damage dealt by 114&#37; for next 5 spells. 30 seconds cooldown.');
_('The long study of the arcane ways have made you a master of spell casting. Performs a guaranteed hit and increases the damage dealt by 117&#37; for next 5 spells. 30 seconds cooldown.');
_('The long study of the arcane ways have made you a master of spell casting. Performs a guaranteed hit and increases the damage dealt by 120&#37; for next 5 spells. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt with your attacks by 74&#37;. Causes your healing spells to heal yourself and an additional nearby ally with 82&#37; of the original heal amount. Lasts 10 seconds. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt with your attacks by 79&#37;. Causes your healing spells to heal yourself and an additional nearby ally with 83&#37; of the original heal amount. Lasts 10 seconds. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt with your attacks by 83&#37;. Causes your healing spells to heal yourself and an additional nearby ally with 85&#37; of the original heal amount. Lasts 10 seconds. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt with your attacks by 88&#37;. Causes your healing spells to heal yourself and an additional nearby ally with 86&#37; of the original heal amount. Lasts 10 seconds. 30 seconds cooldown.');
_('Performs a guaranteed hit and increases the damage dealt with your attacks by 92&#37;. Causes your healing spells to heal yourself and an additional nearby ally with 88&#37; of the original heal amount. Lasts 10 seconds. 30 seconds cooldown.');
_('Establishes an equilibrium between arcane and holy flows. Performs a guaranteed hit and increases the damage dealt by 68&#37; for all attacks within 15 seconds. Heals yourself afterwards for 73&#37; of damage taken in this time. 40 seconds cooldown.');
_('Establishes an equilibrium between arcane and holy flows. Performs a guaranteed hit and increases the damage dealt by 69&#37; for all attacks within 15 seconds. Heals yourself afterwards for 76&#37; of damage taken in this time. 40 seconds cooldown.');
_('Establishes an equilibrium between arcane and holy flows. Performs a guaranteed hit and increases the damage dealt by 70&#37; for all attacks within 15 seconds. Heals yourself afterwards for 80&#37; of damage taken in this time. 40 seconds cooldown.');
_('Establishes an equilibrium between arcane and holy flows. Performs a guaranteed hit and increases the damage dealt by 71&#37; for all attacks within 15 seconds. Heals yourself afterwards for 83&#37; of damage taken in this time. 40 seconds cooldown.');
_('Establishes an equilibrium between arcane and holy flows. Performs a guaranteed hit and increases the damage dealt by 72&#37; for all attacks within 15 seconds. Heals yourself afterwards for 86&#37; of damage taken in this time. 40 seconds cooldown.');
